[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "googlemaps==4.10.0",
    "pandas==2.2.3",
    "requests==2.32.3",
]
