[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Brendan Reed"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "googlemaps==4.10.0",
    "gunicorn>=23.0.0",
    "pandas==2.2.3",
    "requests==2.32.3",
]
